spring:
  devtools:
    add-properties: true
  docker:
    compose:
      enabled: true
      lifecycle-management: start_only
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  sql:
    init:
      mode: always
      continue-on-error: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    br.com.samueltorga.orderprocessing: TRACE
    #com.zaxxer.hikari: DEBUG
    #org.hibernate: TRACE
