spring:
  devtools:
    add-properties: true
  docker:
    compose:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.zaxxer.hikari: TRACE
    org.hibernate.SQL: TRACE
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR
    br.com.samueltorga.orderprocessing: TRACE