spring:
  devtools:
    add-properties: true
  docker:
    compose:
      enabled: true
      lifecycle-management: start_only
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      data-locations: classpath:db-init.sql
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    br.com.samueltorga.orderprocessing: TRACE
