spring:
  application:
    name: order-processing
  devtools:
    add-properties: false
  docker:
    compose:
      enabled: false

  jpa:
    open-in-view: false

  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
      driver-class-name: com.mysql.cj.jdbc.Driver
    master:
      url: jdbc:mysql://localhost:3306/order_processing
      username: appuser
      password: appsecret

    replica:
      url: jdbc:mysql://localhost:3316/order_processing
      username: appuser
      password: appsecret